#lang br/quicklang

(require racket/gui/base)
(require racket/draw)
(require racket/set)
(require "./expander-helpers/game.rkt")
(require "./expander-helpers/renderer.rkt")

; Will be set by reading in map
(define inner-map-index 0)

; The game's rendering component
(define renderer (new puzzler-renderer%))

; Our single game object which contains 
(define puzzler-game (new puzzler-game%
                          [renderer renderer]))

; Gui setup things
(define game-frame (new frame%
                        [label "Game"]
                        [width (get-field window-size renderer)]
                        [height (get-field window-size renderer)]))

; Need to override canvas so we have our key event handler function
(define canvas-with-events%
  (class canvas%
    (define/override (on-char key-event)
     (handle-key-press (send key-event get-key-code)))
    (super-new)))

; What will be called every time the draw callback is needed
(define (paint-to-canvas canvas dc)
  (send dc set-pen "black" 2 'solid)
  (send renderer draw-game-grid dc)
  (draw-game-state dc))

; The game canvas which handles input and drawing callback
(define game-canvas (new canvas-with-events%
                         [parent game-frame]
                         [paint-callback paint-to-canvas]))

; Macros for expansion
(define-macro (puzzler-module-begin PARSE-TREE)
  #'(#%module-begin
     PARSE-TREE))
(provide (rename-out [puzzler-module-begin #%module-begin]))                               

(define-macro (puzzler-program LINE ...)
  #'(void LINE ...))
(provide puzzler-program)

; Map macros, to build map data structure
(define-macro (puzzler-map ROW ...)
  (with-pattern ([CALLER-STX (syntax->datum caller-stx)])
    #'(let ([calling-pattern 'CALLER-STX])
        (send renderer setup-draw-calculations! (length (cdr calling-pattern)))
        (init-map-vector (length (cdr calling-pattern)))
        ROW ...)))
(provide puzzler-map)

(define-macro (map-row CELL ...)
  #'(build-row CELL ...))
(provide map-row)

; Draw macros, sets up char -> image map
(define-macro (draw-block RULE ...)
  #'(void RULE ...))
(provide draw-block)

(define-macro (draw-rule CHAR PATH)
  #'(send puzzler-game add-to-entity-image-table! CHAR PATH))
(provide draw-rule)

; Action (key presses) macros
(define-macro (action-block RULE ...)
  #'(void RULE ...))
(provide action-block)

(define-macro (action-rule ID INPUT DX DY)
  #'(send puzzler-game add-to-action-table! ID INPUT DX DY))
(provide action-rule)

; Interactions macros
(define-macro (interactions-block RULE ...)
  #'(void RULE ...))
(provide interactions-block)

(define-macro (interaction-rule ACTOR INTERACTION RECEIVER)
  #'(send puzzler-game add-to-interaction-table! ACTOR INTERACTION RECEIVER))
(provide interaction-rule)

(define-macro (win-block RULE ...)
  #'(void RULE ...))
(provide win-block)

(define-macro (win-rule FIRST-ID RULE SECOND-ID)
  #'(send puzzler-game add-to-win-rule-table! FIRST-ID RULE SECOND-ID))
(provide win-rule)

(define-macro (events-block RULE ...)
  #'(void RULE ...))
(provide events-block)

(define-macro (event-rule ACTOR EVENT RESULT)
  #'(send puzzler-game add-to-event-table! ACTOR EVENT RESULT))
(provide event-rule)

; Helpers (calls generated by macros)
(define (init-map-vector len)
  (send puzzler-game set-map-vector! (make-vector len (vector "")))
  (send puzzler-game set-initial-game-grid! (make-vector len (vector ""))))

(define (build-row cell . rest)
  (let ([cells (cons cell rest)])
    (for-each (lambda (cell x-pos)
                (cond
                  [(not (string=? cell "#"))
                   (send puzzler-game add-to-position-table! cell x-pos inner-map-index)
                   (send puzzler-game add-to-initial-position-table! cell x-pos inner-map-index)]
                  [else (void)]))
              cells (build-list (length cells) values))
    (vector-set! (get-field map-vector puzzler-game) inner-map-index (list->vector cells))
    (vector-set! (get-field initial-game-grid puzzler-game) inner-map-index (list->vector cells))
    (set! inner-map-index (add1 inner-map-index))))

(define (draw-game-state dc)
  (let* ([image-table (get-field entity-image-table puzzler-game)]
         [block-size (get-field block-size renderer)]
         [block-positions (get-field block-positions renderer)])
  (send dc set-brush "black" 'solid)
  (for-each (lambda (y-draw grid-row)
              (for-each (lambda (x-draw grid-space)
                          (if (and (hash-has-key? image-table grid-space) (not (string=? grid-space "#")))
                              (let ([path (hash-ref image-table grid-space)])
                                (if (string=? path "rect")
                                    (send dc draw-rectangle x-draw y-draw block-size block-size)
                                    (send dc draw-bitmap (read-bitmap path) x-draw y-draw)))
                              (void)))
                        block-positions (vector->list grid-row)))
            block-positions (vector->list (get-field map-vector puzzler-game))))
  (send dc set-brush "white" 'solid))

(define (proceed-with-movement id x y dx dy)
  (hash-set! (get-field position-table puzzler-game) id
             (map (lambda (pos)
                    (cond
                      [(and (= (first pos) x) (= (second pos) y))
                       (send puzzler-game update-grid-space! "#" (first pos) (second pos))
                       (send puzzler-game update-grid-space! id (+ (first pos) dx) (- (second pos) dy))
                       (list (+ (first pos) dx) (- (second pos) dy))]
                      [else
                       (list (first pos) (second pos))]))
                  (hash-ref (get-field position-table puzzler-game) id))))

(define (can-push? id x y dx dy)
  (let* ([interaction-table (get-field interaction-table puzzler-game)]
         [dest-x (+ x dx)]
         [dest-y (- y dy)]
         [dest-val (send puzzler-game get-grid-space dest-x dest-y)]
         [dest-val-empty? (string=? dest-val "#")])
    (cond
      ; TODO: weird pattern of #t #f #t #f, we can probably simplify this
      [dest-val-empty? (proceed-with-movement id x y dx dy) #t]
      [(not (send puzzler-game in-bounds? dest-x dest-y)) #f]
      [(string=? (interaction-rule-str (car (filter (lambda (i) (string=? dest-val (interaction-receiver i))) (hash-ref interaction-table id)))) "grab") (proceed-with-movement id x y dx dy) #t]
      [(not (string=? (interaction-rule-str (car (filter (lambda (i) (string=? dest-val (interaction-receiver i))) (hash-ref interaction-table id)))) "push")) #f]
      [(can-push? id dest-x dest-y dx dy)
       (proceed-with-movement id x y dx dy) #t]
      [else #f])))
       
(define (handle-key-press key)
  (let ([key-str (~a key)]
        [action-table (get-field action-table puzzler-game)]
        [interaction-table (get-field interaction-table puzzler-game)])
    (cond
      [(string=? key-str "r")
       (send puzzler-game restart-game)]
      [(hash-has-key? action-table key-str)
       (for-each (lambda (action)
                   (let* ([id (action-entity action)]
                          [dx (string->number (action-dx action))]
                          [dy (string->number (action-dy action))])
                     (hash-set! (get-field position-table puzzler-game) id
                                (map (lambda (pos)
                                       (let* ([x (first pos)]
                                              [y (second pos)]
                                              [dest-x (+ x dx)]
                                              [dest-y (- y dy)]
                                              [dest-val (send puzzler-game get-grid-space dest-x dest-y)]
                                              [interaction (filter (lambda (i) (string=? dest-val (interaction-receiver i))) (hash-ref interaction-table id))]
                                              [on-exit-action (filter (lambda (i) (string=? "onexit" (interaction-rule-str i))) (hash-ref interaction-table id))] 
                                              [dest-val-empty? (string=? dest-val "#")]
                                              [has-interaction? (> (length interaction) 0)]) 
                                         (cond
                                           [(and has-interaction? (and (string=? (interaction-rule-str (car interaction)) "push") (can-push? dest-val dest-x dest-y dx dy)))
                                            (send puzzler-game update-grid-space! "#" x y)
                                            (send puzzler-game update-grid-space! id dest-x dest-y)
                                            ; Trigger events must be called after all other movement logic for this pass
                                            (trigger-events id x y)
                                            (list dest-x dest-y)]
                                           [(and has-interaction? (string=? (interaction-rule-str (car interaction)) "grab"))
                                            (send puzzler-game update-grid-space! "#" x y)
                                            (send puzzler-game remove-from-position-table! (interaction-receiver (car interaction)) dest-x dest-y)
                                            (send puzzler-game update-grid-space! id dest-x dest-y)
                                            (trigger-events id x y)                                     
                                            (list dest-x dest-y)]
                                           [dest-val-empty?
                                            (send puzzler-game update-grid-space! "#" x y)
                                            (send puzzler-game update-grid-space! id dest-x dest-y)
                                            (trigger-events id x y)
                                            (list dest-x dest-y)]
                                           [else
                                            (list (first pos) (second pos))])))
                                     (hash-ref (get-field position-table puzzler-game) id)))))
                 (hash-ref action-table key-str))]
      [else (void)]))
  (handle-win-rules)
  (send game-canvas refresh-now))

; Performs all events for a given actor entity
(define (trigger-events actor x y)
  (let ([event-table (get-field event-table puzzler-game)])
    (if (hash-has-key? event-table actor)
        (for-each (lambda (event) (trigger-event actor x y event)) (hash-ref event-table actor))
        (void))))

; Performs actions for a single event
(define (trigger-event actor x y event)
  (let* ([rule (event-rule-str event)]
         [result (event-result event)])
    (cond
      [(string=? rule "onexit")
       (send puzzler-game update-grid-space-and-position-table! result x y)])))

(define (handle-win-rules)
  (let* ([win-rule-table (get-field win-rule-table puzzler-game)])
  (if (get-field win-flag puzzler-game)
      (writeln "YOU WIN!!!")
      (for-each (lambda (rule)
                  (if (string=? rule "count_items")
                      (for-each (lambda (ids)
                              (let* ([first-id (first ids)]
                                     [second-id (second ids)]
                                     [target-count (string->number second-id)]
                                     [object-positions (hash-ref (get-field position-table puzzler-game) first-id)])
                                (if (= target-count (length object-positions))
                                    (send puzzler-game set-game-win-flag! #t)
                                    (void))))
                                (hash-ref win-rule-table rule))
                      (for-each (lambda (ids)
                              (let* ([game-position-table (get-field position-table puzzler-game)]
                                     [first-id (first ids)]
                                     [second-id (second ids)]
                                     [first-positions (hash-ref game-position-table first-id)]
                                     [second-positions (hash-ref game-position-table second-id)])
                                (if (same-position? first-positions second-positions)
                                    (send puzzler-game set-game-win-flag! #t)
                                    (void))))
                            (hash-ref win-rule-table rule))))
                  (hash-keys win-rule-table)))))

(define (same-position? pos-list1 pos-list2)
  (let* ([pos-set1 (list->set pos-list1)]
         [pos-set2 (list->set pos-list2)]
         [same-positions (set-intersect pos-set1 pos-set2)])
    (> (set-count same-positions) 0)))

(send game-frame show #t)